name: Bug Report
description: Report Frost bugs, stack traces or other behavior related issues.
body:
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to Recreate (if known)
      description: This must include a video, or detailed instructions to help re-create the issue. Anything helps!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Stack trace
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        If you prefer, you can use a paste site like https://pastebin.com/.
      value: |
        ```
        paste your stack trace or a https://pastebin.com/ link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Frost version
      description: Execute the /frost command and it will output the current Frost version you are running.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
